core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from shop.forms import MyPasswordResetForm, MySetPasswordForm
from shop import views
from shop import webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),


    path('password_reset/', auth_view.PasswordResetView.as_view(template_name='shop/password_reset.html', form_class=MyPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='shop/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='shop/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='shop/password_reset_complete.html'), name="password-reset-complete"),

    #Ajax 
    path('pluscart/', views.pluscart, name='plus-cart'),
    path('minuscart/', views.minuscart, name='minus-cart'),
    path('removecart/', views.removecart, name='remove-cart'),
    path('pluswishlist/', views.plus_wishlist, name='plus_wishlist'),
    path('minuswishlist/', views.minus_wishlist, name='minus_wishlist'),
    path('payment/webhook/', webhook.stripe_webhook, name="stripe-webhook"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Neel Shop'
admin.site.site_title = 'Neel shop'
admin.site.site_index_title = 'Neel shop'

shop/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeDoneView, PasswordChangeView, LogoutView
from django.contrib.auth import views as auth_view
from .forms import LoginForm, MyPasswordResetForm, MyPasswordChangeForm, MySetPasswordForm
from . import webhook

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:val>/', views.CategoryView.as_view(), name='category'),
    path('category-title/<str:val>/', views.CategoryTitleView.as_view(), name='category-title'),
    path('product-detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('register/', views.CustomerRegisterView.as_view(), name="register"),
    path('account/login/', LoginView.as_view(template_name='shop/login.html', authentication_form=LoginForm), name='login'),
    path('password-reset/', PasswordResetView.as_view(template_name='shop/password_reset.html', form_class=MyPasswordResetForm), name='password-reset'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('udpdate-profile/<int:pk>/', views.updateProfileView.as_view(), name='update-profile'),
    path('passwordchange/', PasswordChangeView.as_view(template_name='shop/change-password.html', form_class=MyPasswordChangeForm, success_url=reverse_lazy('shop:passwordchangedone')), name='changepassword'),
    path('passwordchangedone/', PasswordChangeDoneView.as_view(template_name='shop/password-change-done.html'), name='passwordchangedone'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('shop:login')), name='logout'),

    # Add to cart
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('show_cart/', views.show_cart, name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('process/', views.payment_process, name="process"),
    path('success/', views.payment_success, name="sucess"),
    path('cancel/', views.payment_cancel, name='cancel'),

    #About and contact
    path('about/', views.about, name='about'),
]

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from .models import Customer

class LoginForm(AuthenticationForm):
	username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': 'True'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))

class CustomerRegForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

	class Meta:
		model = User
		fields = ['username', 'password1', 'password2', 'email']


class MyPasswordChangeForm(PasswordChangeForm):
	old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete':'current-password'}))
	new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))
	new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete':'current-password'}))


class MyPasswordResetForm(PasswordResetForm):
	email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))


class MySetPasswordForm(SetPasswordForm):
	new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))
	new_password2 = forms.CharField(label='Confirm new password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))


class CustomerProfileForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = ['name', 'locality','number', 'city', 'zipcode', 'state']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'city': forms.TextInput(attrs={'class': 'form-control'}),
			'locality': forms.TextInput(attrs={'class': 'form-control'}),
			'number': forms.NumberInput(attrs={'class': 'form-control'}),
			'zipcode': forms.NumberInput(attrs={'class': 'form-control'}),
			'state': forms.Select(attrs={'class': 'form-control'}),
		}
			
	

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Customer, Cart, Order, OrderItem, Wishlist
from django.db.models import Count, Q
from .forms import CustomerRegForm, CustomerProfileForm
from django.contrib import messages
from django.http import JsonResponse
import stripe
from django.conf import settings
from django.urls import reverse
from decimal import Decimal

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def home(request):
    user = request.user
    
    totalitem = 0
    totalwish = 0
    if user.is_authenticated:
        totalitem = len(Cart.objects.filter(user=user))
        totalwish = len(Wishlist.objects.filter(user=user))
    return render(request, 'shop/home.html', locals())


class CategoryView(View):
    def get(self, request, val):
        product = Product.objects.filter(category=val)
        titles = product.values('title').annotate(total=Count('title'))
        return render(request, 'shop/category.html', locals())
    

class CategoryTitleView(View):
    def get(self, request, val):
        product = Product.objects.filter(title=val)
        titles = Product.objects.filter(category=product[0].category).values('title')
        return render(request, 'shop/category.html', locals())
    

class ProductDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        wishlist = Wishlist.objects.filter(Q(product=product) & Q(user=request.user))
        return render(request, 'shop/product_detail.html', locals())


class CustomerRegisterView(View):

    def get(self, request):
        form = CustomerRegForm()
        return render(request, 'shop/customer_reg.html', locals())

    def post(self, request):
        form = CustomerRegForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulation, your profile is created')
        else:
            messages.error(request, 'Invalid, what is happened')

        return render(request, 'shop/customer_reg.html', locals())


class ProfileView(View):

    def get(self, request):
        form = CustomerProfileForm()
        return render(request, 'shop/profile.html', locals())
    def post(self, request):
        form = CustomerProfileForm(request.POST)
        if form.is_valid():
            user = request.user
            name = form.cleaned_data['name']
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            zipcode = form.cleaned_data['zipcode']
            state = form.cleaned_data['state']
            number = form.cleaned_data['number']
            new_customer = Customer(user=user, name=name, locality=locality, city=city, number=number, zipcode=zipcode, state=state)
            new_customer.save()
            messages.success(request, 'Congratulation, Profile save successfulled!')
        else:
            messages.error(request, 'Invalid Profile.')
        return render(request, 'shop/profile.html', locals())


class AddressView(View):
    def get(self, request):
        add = Customer.objects.filter(user=request.user)
        return render(request, 'shop/address.html', locals())

class updateProfileView(View):
    def get(self, request, pk):
        add = Customer.objects.get(pk=pk)
        form = CustomerProfileForm(instance=add)
        return render(request, 'shop/update_profile.html', locals())

    def post(self, request, pk):
        form = CustomerProfileForm(request.POST)
        if form.is_valid():
            add = Customer.objects.get(pk=pk)
            add.name = form.cleaned_data['name']
            add.locality = form.cleaned_data['locality']
            add.city = form.cleaned_data['city']
            add.zipcode = form.cleaned_data['zipcode']
            add.state = form.cleaned_data['state']
            add.number = form.cleaned_data['number']
            add.save()
            messages.success(request, 'Congratulation, Profile save successfulled!')
        else:
            messages.error(request, 'Invalid Profile.')
        return redirect('shop:address')


# Add to cart view
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('product_id')
    product = Product.objects.get(id=product_id)
    Cart(user=user, product=product).save()
    return redirect('shop:cart')
    

#Show cart vue
def show_cart(request):
    user = request.user
    cart = Cart.objects.filter(user=user)
    total = len(cart)
    amount = 0
    for p in cart:
        value = p.quantity * p.product.discount_price
        amount += value
    totalamount = amount + 40
    return render(request, 'shop/cart.html', locals())


#checkout view
class CheckoutView(View):
    def get(self, request):
        user = request.user
        add = Customer.objects.filter(user=user)
        cart_items = Cart.objects.filter(user=user)
        amount = 0
        for p in cart_items:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40
        return render(request, 'shop/checkout.html', locals())

    def post(self, request):
        user = request.user
        add_id = request.POST.get('custid')
        customer = Customer.objects.filter(user=user)
        add = customer.get(id=add_id)
       
        cart = Cart.objects.filter(user=user)
        order = Order.objects.create(user=user, customer=add)
        order.save()
        amount = 0
        for item in cart:
            OrderItem.objects.create(order=order, product=item.product, quantity=item.quantity)
            value = item.quantity * item.product.discount_price
            amount += value
        totalamount = amount + 40
        request.session['order_id'] = order.id
        return redirect(reverse('shop:process'))


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    user = request.user
    cart = Cart.objects.filter(user=user)
    amount = 0
    for item in cart:
        value = item.quantity * item.product.discount_price
        amount += value
    totalamount = amount + 40
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('shop:sucess'))
        cancel_url = request.build_absolute_uri(reverse('shop:cancel'))
        session_data = {
            'mode': 'payment',
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [],
            'metadata': {
                'order_id': order_id,
            }
        }
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.product.discount_price * 100),
                    'currency': 'usd',
                    'product_data': {
                    'name': item.product.title,
                    }
                },
                'quantity': item.quantity,
                })
        # Ajouter une ligne pour les frais d'expédition
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': 4000,  # Le prix de 40 euros en cents
                'currency': 'usd',    # La devise utilisée pour les frais d'expédition
                'product_data': {
                    'name': 'Frais d\'expédition',
                },
            },
            'quantity': 1,
        })
        #create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        cart.delete() 
        return redirect(session.url, code=303)
    else:
        return render(request, 'shop/process.html', locals())


# Increment quantity
def pluscart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=request.user))
        c.quantity += 1
        c.save()
        user = request.user
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40

        data={
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount

        }
        return JsonResponse(data)

#Decrement quantity
def minuscart(request):
    if  request.method == "GET":
        user = request.user
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=user))
        if c.quantity > 1:
            c.quantity -= 1
        c.save()
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40
        data = {
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount,
            'deleted': False
        }
        return JsonResponse(data)

# Remove items
def removecart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=request.user))
        c.delete()
        user = request.user
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40

        data={
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount

        }
        return JsonResponse(data)


def payment_success(request):
    return render(request, 'shop/completed.html')


def payment_cancel(request):
    return render(request, 'shop/canceled.html')


def about(request):
    return render(request, 'shop/about.html', locals())


def plus_wishlist(request):

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <!-- style sheets -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Diary Product - {% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- navbar -->

    <nav class="navbar navbar-expand-lg navbar-light bg-success">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:home' %}">
          <img
            src="{% static 'images/Neel.png' %}"
            alt=""
            style="height: 70px; width: 70px"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'shop:home' %}"
                >Home</a
              >
            </li>
            {% if user.is_authenticated %}

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Products
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'ML'%}"
                    >Milk</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'CR'%}"
                    >Curd</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'MS'%}"
                    >MilkShake</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'GH'%}"
                    >Ghee</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'PN'%}"
                    >Paneer</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'CZ'%}"
                    >Cheese</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'IC'%}"
                    >Ice-Creams</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:category' 'LS'%}"
                    >Lassi</a
                  >
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact Us</a>
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dino
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'shop:profile' %}"
                    >Profile</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="">Orders</a>
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'shop:changepassword' %}"
                    >Change Password</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'shop:logout' %}"
                    >Logout</a
                  >
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:cart' %}"
                ><span class="badge bg-danger"
                  >{% if totalitem > 0 %} {{totalitem}} {% endif %}</span
                ><i class="fas fa-shopping-cart"></i
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"
                ><span class="badge bg-danger"
                  >{% if totalwish > 0 %} {{ totalwish}} {% endif %}</span
                ><i class="fas fa-heart"></i
              ></a>
            </li>
            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:register' %}"
                >Registration</a
              >
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- end navbar -->
    <!-- block slider -->
    {% block slider %} {% endblock slider %}
    <!-- block information -->
    {% block information %} {% endblock information %}
    <!-- block content -->
    {% block content %} {% endblock content %}
    <!-- end block -->

    <!-- footer -->
    <footer
      class="fixed-bottom container-fluid bg-success text-center p-2 mt-5"
    >
      Copyright &copy; 2023 | Develop by Diarra
    </footer>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
      integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/myscript.js' %}"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <!-- Optional JavaScript -->

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>