core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from shop.forms import MyPasswordResetForm, MySetPasswordForm
from shop import views
from shop import webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),


    path('password_reset/', auth_view.PasswordResetView.as_view(template_name='shop/password_reset.html', form_class=MyPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='shop/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='shop/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='shop/password_reset_complete.html'), name="password-reset-complete"),

    #Ajax 
    path('pluscart/', views.pluscart, name='plus-cart'),
    path('minuscart/', views.minuscart, name='minus-cart'),
    path('removecart/', views.removecart, name='remove-cart'),
    path('pluswishlist/', views.plus_wishlist, name='plus_wishlist'),
    path('minuswishlist/', views.minus_wishlist, name='minus_wishlist'),
    path('payment/webhook/', webhook.stripe_webhook, name="stripe-webhook"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Neel Shop'
admin.site.site_title = 'Neel shop'
admin.site.site_index_title = 'Neel shop'

shop/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeDoneView, PasswordChangeView, LogoutView
from django.contrib.auth import views as auth_view
from .forms import LoginForm, MyPasswordResetForm, MyPasswordChangeForm, MySetPasswordForm
from . import webhook

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:val>/', views.CategoryView.as_view(), name='category'),
    path('category-title/<str:val>/', views.CategoryTitleView.as_view(), name='category-title'),
    path('product-detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('register/', views.CustomerRegisterView.as_view(), name="register"),
    path('account/login/', LoginView.as_view(template_name='shop/login.html', authentication_form=LoginForm), name='login'),
    path('password-reset/', PasswordResetView.as_view(template_name='shop/password_reset.html', form_class=MyPasswordResetForm), name='password-reset'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('udpdate-profile/<int:pk>/', views.updateProfileView.as_view(), name='update-profile'),
    path('passwordchange/', PasswordChangeView.as_view(template_name='shop/change-password.html', form_class=MyPasswordChangeForm, success_url=reverse_lazy('shop:passwordchangedone')), name='changepassword'),
    path('passwordchangedone/', PasswordChangeDoneView.as_view(template_name='shop/password-change-done.html'), name='passwordchangedone'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('shop:login')), name='logout'),

    # Add to cart
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('show_cart/', views.show_cart, name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('process/', views.payment_process, name="process"),
    path('success/', views.payment_success, name="sucess"),
    path('cancel/', views.payment_cancel, name='cancel'),

    #About and contact
    path('about/', views.about, name='about'),
]

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from .models import Customer

class LoginForm(AuthenticationForm):
	username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': 'True'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))

class CustomerRegForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

	class Meta:
		model = User
		fields = ['username', 'password1', 'password2', 'email']


class MyPasswordChangeForm(PasswordChangeForm):
	old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete':'current-password'}))
	new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))
	new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete':'current-password'}))


class MyPasswordResetForm(PasswordResetForm):
	email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))


class MySetPasswordForm(SetPasswordForm):
	new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))
	new_password2 = forms.CharField(label='Confirm new password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}))


class CustomerProfileForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = ['name', 'locality','number', 'city', 'zipcode', 'state']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'city': forms.TextInput(attrs={'class': 'form-control'}),
			'locality': forms.TextInput(attrs={'class': 'form-control'}),
			'number': forms.NumberInput(attrs={'class': 'form-control'}),
			'zipcode': forms.NumberInput(attrs={'class': 'form-control'}),
			'state': forms.Select(attrs={'class': 'form-control'}),
		}
			
	

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Customer, Cart, Order, OrderItem, Wishlist
from django.db.models import Count, Q
from .forms import CustomerRegForm, CustomerProfileForm
from django.contrib import messages
from django.http import JsonResponse
import stripe
from django.conf import settings
from django.urls import reverse
from decimal import Decimal

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def home(request):
    user = request.user
    
    totalitem = 0
    totalwish = 0
    if user.is_authenticated:
        totalitem = len(Cart.objects.filter(user=user))
        totalwish = len(Wishlist.objects.filter(user=user))
    return render(request, 'shop/home.html', locals())


class CategoryView(View):
    def get(self, request, val):
        product = Product.objects.filter(category=val)
        titles = product.values('title').annotate(total=Count('title'))
        return render(request, 'shop/category.html', locals())
    

class CategoryTitleView(View):
    def get(self, request, val):
        product = Product.objects.filter(title=val)
        titles = Product.objects.filter(category=product[0].category).values('title')
        return render(request, 'shop/category.html', locals())
    

class ProductDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        wishlist = Wishlist.objects.filter(Q(product=product) & Q(user=request.user))
        return render(request, 'shop/product_detail.html', locals())


class CustomerRegisterView(View):

    def get(self, request):
        form = CustomerRegForm()
        return render(request, 'shop/customer_reg.html', locals())

    def post(self, request):
        form = CustomerRegForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulation, your profile is created')
        else:
            messages.error(request, 'Invalid, what is happened')

        return render(request, 'shop/customer_reg.html', locals())


class ProfileView(View):

    def get(self, request):
        form = CustomerProfileForm()
        return render(request, 'shop/profile.html', locals())
    def post(self, request):
        form = CustomerProfileForm(request.POST)
        if form.is_valid():
            user = request.user
            name = form.cleaned_data['name']
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            zipcode = form.cleaned_data['zipcode']
            state = form.cleaned_data['state']
            number = form.cleaned_data['number']
            new_customer = Customer(user=user, name=name, locality=locality, city=city, number=number, zipcode=zipcode, state=state)
            new_customer.save()
            messages.success(request, 'Congratulation, Profile save successfulled!')
        else:
            messages.error(request, 'Invalid Profile.')
        return render(request, 'shop/profile.html', locals())


class AddressView(View):
    def get(self, request):
        add = Customer.objects.filter(user=request.user)
        return render(request, 'shop/address.html', locals())

class updateProfileView(View):
    def get(self, request, pk):
        add = Customer.objects.get(pk=pk)
        form = CustomerProfileForm(instance=add)
        return render(request, 'shop/update_profile.html', locals())

    def post(self, request, pk):
        form = CustomerProfileForm(request.POST)
        if form.is_valid():
            add = Customer.objects.get(pk=pk)
            add.name = form.cleaned_data['name']
            add.locality = form.cleaned_data['locality']
            add.city = form.cleaned_data['city']
            add.zipcode = form.cleaned_data['zipcode']
            add.state = form.cleaned_data['state']
            add.number = form.cleaned_data['number']
            add.save()
            messages.success(request, 'Congratulation, Profile save successfulled!')
        else:
            messages.error(request, 'Invalid Profile.')
        return redirect('shop:address')


# Add to cart view
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('product_id')
    product = Product.objects.get(id=product_id)
    Cart(user=user, product=product).save()
    return redirect('shop:cart')
    

#Show cart vue
def show_cart(request):
    user = request.user
    cart = Cart.objects.filter(user=user)
    total = len(cart)
    amount = 0
    for p in cart:
        value = p.quantity * p.product.discount_price
        amount += value
    totalamount = amount + 40
    return render(request, 'shop/cart.html', locals())


#checkout view
class CheckoutView(View):
    def get(self, request):
        user = request.user
        add = Customer.objects.filter(user=user)
        cart_items = Cart.objects.filter(user=user)
        amount = 0
        for p in cart_items:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40
        return render(request, 'shop/checkout.html', locals())

    def post(self, request):
        user = request.user
        add_id = request.POST.get('custid')
        customer = Customer.objects.filter(user=user)
        add = customer.get(id=add_id)
       
        cart = Cart.objects.filter(user=user)
        order = Order.objects.create(user=user, customer=add)
        order.save()
        amount = 0
        for item in cart:
            OrderItem.objects.create(order=order, product=item.product, quantity=item.quantity)
            value = item.quantity * item.product.discount_price
            amount += value
        totalamount = amount + 40
        request.session['order_id'] = order.id
        return redirect(reverse('shop:process'))


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    user = request.user
    cart = Cart.objects.filter(user=user)
    amount = 0
    for item in cart:
        value = item.quantity * item.product.discount_price
        amount += value
    totalamount = amount + 40
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('shop:sucess'))
        cancel_url = request.build_absolute_uri(reverse('shop:cancel'))
        session_data = {
            'mode': 'payment',
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [],
            'metadata': {
                'order_id': order_id,
            }
        }
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.product.discount_price * 100),
                    'currency': 'usd',
                    'product_data': {
                    'name': item.product.title,
                    }
                },
                'quantity': item.quantity,
                })
        # Ajouter une ligne pour les frais d'expédition
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': 4000,  # Le prix de 40 euros en cents
                'currency': 'usd',    # La devise utilisée pour les frais d'expédition
                'product_data': {
                    'name': 'Frais d\'expédition',
                },
            },
            'quantity': 1,
        })
        #create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        cart.delete() 
        return redirect(session.url, code=303)
    else:
        return render(request, 'shop/process.html', locals())


# Increment quantity
def pluscart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=request.user))
        c.quantity += 1
        c.save()
        user = request.user
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40

        data={
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount

        }
        return JsonResponse(data)

#Decrement quantity
def minuscart(request):
    if  request.method == "GET":
        user = request.user
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=user))
        if c.quantity > 1:
            c.quantity -= 1
        c.save()
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40
        data = {
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount,
            'deleted': False
        }
        return JsonResponse(data)

# Remove items
def removecart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user=request.user))
        c.delete()
        user = request.user
        cart = Cart.objects.filter(user=user)
        amount = 0
        for p in cart:
            value = p.quantity * p.product.discount_price
            amount += value
        totalamount = amount + 40

        data={
            'quantity': c.quantity,
            'amount': amount,
            'totalamount': totalamount

        }
        return JsonResponse(data)


def payment_success(request):
    return render(request, 'shop/completed.html')


def payment_cancel(request):
    return render(request, 'shop/canceled.html')


def about(request):
    return render(request, 'shop/about.html', locals())


def plus_wishlist(request):

shop/templates/shop/address.html
{% extends "base.html" %}
<!-- -->
{% block title %} address {% endblock title %}
<!-- -->
{% block content %}
<div class="container my-5">
	<div class="row">
		<h3>Welcome <span class="text-capitalize">{{request.user }}</span></h3>
		<br /><br />
		<div class="col-sm-2 border-end">
			<ul class="list-unstyled">
				<li class="d-grid">
					<a href="{% url 'shop:profile' %}" class="btn">Profile</a>
				</li>
				<li class="d-grid">
					<a href="{% url 'shop:address' %}" class="btn btn-primary"
						>Address</a
					>
				</li>
			</ul>
		</div>
		<div class="col-sm-8 offset-1">
			<div class="row">
				{% for ad in add %}
				<div class="col-sm-6">
					<div class="card m-2">
						<div class="card-body">
							<h3 class="card-title">Address: {{ forloop.counter }}</h5>
							
							<p>name: {{ ad.name }}</p>
							<p>Locality: {{ ad.locality }}</p>
							<p>Mobile: {{ ad.number }}</p>
							<p>City: {{ ad.city }}</p>
							<p>State: {{ ad.state }}</p>
							<p>Pincode: {{ ad.zipcode }}</p>
							<p class="text-center"> <a href="{% url 'shop:update-profile' pk=ad.id %}" class="btn btn-success">Update</a></p>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}

shop/templates/shop/cart.html
{% extends "base.html" %}

<!-- -->
{% block content %}
<div class="container my-5">
  <div class="row">
    {% if cart %}
    <h3 class="text-center mb-5">Shopping Cart</h3>
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3>Cart</h3>
          {% for item in cart %}
          <div class="row cart-item">
            <div class="col-sm-3 text-center align-self-center">
              <img
                src="{{ item.product.prod_image.url }}"
                alt=""
                class="img-fluid img-thumbnail shadow-sm"
                height="150"
                width="150"
              />
            </div>
            <div class="col-sm-9">
              <div>
                <h5>{{ item.product.title }}</h5>
                <p class="mb-2 text-muted small">
                  {{ item.product.description }}
                </p>
                <div class="my-3">
                  <label for="quantity">Quantity:</label>
                  <a class="minus_cart btn" pid="{{ item.product.id }}"
                    ><i class="fas fa-minus-square fa-lg"></i
                  ></a>
                  <span id="quantity">{{ item.quantity }}</span>
                  <a class="plus_cart btn" pid="{{ item.product.id }}"
                    ><i class="fas fa-plus-square fa-lg"></i
                  ></a>
                </div>
                <div class="d-flex justify-content-between">
                  <a
                    href=""
                    class="remove-cart btn btn-sm btn-secondary mr-3"
                    pid="{{ item.product.id }}"
                    >Remove item</a
                  >
                  <p class="mb-0">
                    <span>
                      <strong>Rs.{{ item.product.discount_price }}</strong>
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <hr class="text-muted" />
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="row">
        <div class="card">
          <div class="card-body">
            <h3 class="text-center">Summary</h3>

            <ul class="list-group">
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-0"
              >
                Amount <span id="amount">Rs.{{ amount }}</span>
              </li>
              <li
                class="list-group-item d-flex justify-content-between align-items-center px-0 border-0"
              >
                Shipping<span>Rs. 40.0</span>
              </li>
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3"
              >
                <div><strong>Total</strong> <small>(including GST)</small></div>
                <span id="totalamount"
                  ><strong>Rs.{{ totalamount }}</strong></span
                >
              </li>
            </ul>
            <div class="d-grid">
              <a href="{% url 'shop:checkout' %}" class="btn btn-primary"
                >Place order</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <h1 class="text-center mb-5">Cart empty</h1>
    {% endif %}
  </div>
</div>
{% endblock content %}

shop/templates/shop/category.html
{% extends "base.html" %}
<br />
{% load static %}
<br />
{% block title %} Category {%endblock title %}
<br />
{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-sm-3">
      <div class="list-group">
        {% for val in titles %}
        <a
          href="{% url 'shop:category-title' val.title %}"
          class="list-group-item list-group-item-action"
          aria-current="true"
        >
          {{ val.title }}
        </a>

        {% endfor %}
      </div>
    </div>
    <div class="col-sm-9">
      <div class="row">
        {% for prod in product %}

        <div class="col text-center mb-4">
          <a href="{% url 'shop:product_detail' prod.id %}" class="btn">
            <div>
              <img
                src="{{ prod.prod_image.url }}"
                width="300px"
                height="200px"
                alt=""
              />
              <div class="fw-bold">{{ prod.title }}</div>
              <div class="fw-bold text-danger">
                Rs.{{ prod.discount_price }}
                <small class="fw-light text-decoration-line-through"
                  >{{ prod.selling_price }}</small
                >
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shop/templates/shop/home.html
{% extends "base.html" %} {% load static %}
<!-- block title -->
{% block title %} Home {% endblock title %}

<!-- block slider -->
{% block slider %}

<div
  id="carouselExampleSlidesOnly"
  class="carousel slide"
  data-bs-ride="carousel"
>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        class="d-block w-100"
        src="{% static 'images/banner/b1.jpg'%}"
        alt="First slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="{% static 'images/banner/b2.jpg' %}"
        alt="Second slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="{% static 'images/banner/b3.jpg' %}"
        alt="Third slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="{% static 'images/banner/b4.jpg' %}"
        alt="Third slide"
      />
    </div>
  </div>
</div>
{% endblock slider %}

<!-- block information -->
{% block information %}
<div class="container">
  <div class="row bg-success text-center p-5 text-white border-bottom shadow">
    <h1 class="text-center">Product</h1>
    <small class="fs-5"
      >Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum tempore
      pariatur earum dolor aperiam. Voluptas, laborum placeat suscipit rem
      voluptates natus omnis adipisci.</small
    >
  </div>
</div>

{% endblock information %}

<!-- block content -->
{% block content %}
<div class="container text-center">
  <h2>Dairy Products</h2>
  <br />
  <br />

  <div class="row container">
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk smbg">
        <a href="{% url 'shop:category' 'GH' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/buffalo-ghee.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">Ghee</p>
          </div>
        </a>
      </div>
    </div>
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk curdbgpro">
        <a href="{% url 'shop:category' 'CR' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/curd-total.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">CURD</p>
          </div>
        </a>
      </div>
    </div>
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk buttermilk">
        <a href="{% url 'shop:category' 'IC' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/kulfi.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">Kuffi</p>
          </div>
        </a>
      </div>
    </div>
  </div>
  <br /><br />
  <div class="row container">
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk smbg">
        <a href="{% url 'shop:category' 'MS' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/milk-shake-chocolate.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">MilkShake</p>
          </div>
        </a>
      </div>
    </div>
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk curdbgpro">
        <a href="{% url 'shop:category' 'ML' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/cow-milk.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">Milk</p>
          </div>
        </a>
      </div>
    </div>
    <div
      class="col-md-4 col-sm-4 mi-go wow fadeInUp"
      data-wow-duration="1s"
      data-wow-delay="0.6s"
      style="
        animation-duration: 1s;
        animation-delay: 0.6s;
        animation-name: none;
      "
    >
      <div class="goodnesssec buttermilk buttermilk">
        <a href="{% url 'shop:category' 'CZ' %}">
          <div class="goodnessseccont text-center">
            <img
              src="{% static 'images/processedcheese.png' %}"
              alt=""
              class="img-responsive center-block"
            />
            <p class="mlkpro">CHEESE</p>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>
<br /><br /><br />
{% endblock content %}

shop/templates/shop/product_detail.html
{% extends "base.html" %}
<br />
{% load static %}
<br />
{% block content %}
<div class="container">
  <div class="row flex justify-content-between">
    <div class="img2 col-lg-5 mt-5">
      <img
        src="{{ product.prod_image.url }}"
        class="col-xs-6 col-sm-12 col-log-12 mt-3 text-sm-center image w-100 h-75"
        alt=""
      />
    </div>
    <div class="productdetail col-lg-5 mt-5">
      <h1 class="fs-2">{{ product.title }}</h1>
      <h5>Rs.{{ product.discount_price }}/-</h5>
      <small class="text-decoration-line-through text-muted fs-5"
        ><del>Rs.{{ product.selling_price}}/-</del></small
      >
      <br /><br />
      <h4>Product Features</h4>
      <ul class="fs-6">
        <li>{{ product.description }}</li>
      </ul>
      <form action="{% url 'shop:add_to_cart' %}" class="d-inline">
        <input type="hidden" name="product_id" value="{{ product.id }}" />
        <button class="btn btn-danger" type="submit">Add to cart</button>
      </form>

      <a
        href="{% url 'shop:cart' %}"
        class="btn btn-warning shadow px-3 py-2 ms-4"
        type="submit"
        >Buy Now</a
      >
      {% if wishlist %}
      <a
        pid="{{ product.id }}"
        class="minus-wishlist btn btn-danger shadow px-3 py-2 ms-4"
        ><i class="fas fa-heart fa-lg"></i
      ></a>
      {% else %}
      <a
        pid="{{ product.id }}"
        class="plus-wishlist btn btn-success shadow px-3 py-2 ms-4"
        ><i class="fas fa-heart fa-lg"></i
      ></a>

      {% endif %}
    </div>
  </div>
</div>
<br />
<br />

{% endblock content %}